stages:
  - deploy

deploy_to_github:
  stage: deploy
  before_script:
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
  script:
    - git remote rm github || true
    - git remote add github https://oauth2:${GITHUB_TOKEN}@github.com/riorul/ITI0105.git
    - git push -f github main
  only:
    - main