stages:
  - deploy

deploy_job:
  stage: deploy
  script:
    - |
      if [ "$CI_COMMIT_BRANCH" == "main" ]; then
        git checkout -b main
        git fetch
        git config --global user.email "$GITLAB_USER_EMAIL"
        git config --global user.name "$GITLAB_USER_NAME"

        # Check if the remote already exists
        if ! git remote | grep -q '^github$'; then
          git remote add github https://github.com/riorul/ITI0105.git
        else
          git remote set-url github https://github.com/riorul/ITI0105.git
        fi

        git push github main
      else
        echo "Skipping deployment as changes were not made to the main branch."
      fi
  only:
    - main