stages:
  - deploy

deploy_to_github:
  stage: deploy
  before_script:
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
  script:
    - git remote -v | grep -q 'github' && git remote set-url github $REMOTE_REPOSITORY_URL || git remote add github $REMOTE_REPOSITORY_URL
    - git checkout main
    - git pull origin main
    - git pull github main
    - git status
    - git push https://root:$ACCESS_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git HEAD:main
  only:
    - main