stages:
  - deploy

deploy_to_github:
  stage: deploy
  script:
    - git clone https://riorul@github.com/riorul/ITI0105.git
    - cd your-github-repo
    - git config --global user.email "$GITLAB_USER_EMAIL"
    - git config --global user.name "$GITLAB_USER_NAME"
    - git checkout main
    - git add .
    - git commit -m "Update from GitLab CI/CD"
    - git push https://$GITHUB_TOKEN@github.com/riorul/ITI0105.git main
  only:
    - main